# Generated by Django 3.2.7 on 2022-09-29 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('image', models.FileField(null=True, upload_to='patient/images')),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('marital_status', models.CharField(max_length=15, null=True)),
                ('blood_group', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField()),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='doctor/images')),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('medical', models.CharField(max_length=25, null=True)),
                ('position', models.CharField(max_length=25, null=True)),
                ('specialities', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('post_date', models.DateField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateField()),
                ('fee', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
                ('patient', models.ManyToManyField(to='appointment.Patient')),
            ],
        ),
    ]
