# Generated by Django 3.2.7 on 2022-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
