# Generated by Django 3.2.7 on 2022-10-02 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='doctor/images')),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('medical', models.CharField(max_length=25, null=True)),
                ('position', models.CharField(max_length=25, null=True)),
                ('specialities', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
